### ISSUE TITLE
Running /back without creating a home drops player in the void

### ISSUE THREAD

**Issue by bluelightning32** [VladoCC/get_back_home#2]
I am running a dungeons, dragons, and space shuttles server, version 4.5a. It includes BackToHome-1.5.jar.

I've had a couple players run /back before running /createhome. They end up falling through the void under the world and are unable to access their grave afterwards. I was able to reproduce it with my account:
1. Delete player.dat file to reset the account.
2. After joining, at first /back correctly shows an error message that no home has been created yet.
3. Either dying or disconnecting and reconnecting to the server incorrectly enables the /back command.
4. Now running /back sends the player to 0, 0, 0.

**Comment by VladoCC** [comment]
Really weird behavior. I will check it as soon as possible, but now I don't have much time.

**Comment by VladoCC** [comment]
I want to know only one thing. How did your players deleted their playerdatas? Because I found that his bug can be reproduced only in one case: if there is no data about player, but he were in thi world, forge tries to restore info about this player from files and it sets every int to 0 if there is no valid info about this int.
So there is no way to find yourself in void without file corruption.

**Comment by VladoCC** [comment]
Sadly, but I can't do anythng about this problem, except of just heck if it tries to create home at 0,0,0 and disallow that.

**Comment by bluelightning32** [comment]
I deleted my playerdata to reproduce the issue with my account. The player data was not deleted for the other users.

I made sure I was logged off when I deleted my player data.

If you really can't reproduce this, can you log a backtrace when the game tries to create a home at 0,0,0? I'll run your new code and give you the log output.

**Comment by VladoCC** [comment]
I fixed it.
